version: "3.9"

networks:
  compras_net:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://89.167.20.163:3001
    container_name: compras-frontend
    ports:
      - "8080:80"
    networks:
      - compras_net
