version: "3.9"
networks:
  compras_net:
    external: true

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compras
      TZ: America/Tegucigalpa       # ðŸ•’ Zona horaria local
      PGTZ: America/Tegucigalpa     # ðŸ•’ PostgreSQL tambiÃ©n usa esta TZ internamente
    ports: ["5455:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - compras_net 

  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: development
    command: pnpm start:dev  
    env_file:
      - ./.env.docker
    environment:
      TZ: America/Tegucigalpa       # ðŸ•’ Zona horaria local para Node/NestJS
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - compras_net 

volumes:
  dbdata:
